# Generated by Django 2.0.4 on 2018-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_index', models.PositiveSmallIntegerField(db_index=True)),
                ('entity', models.CharField(db_index=True, default='', max_length=300)),
                ('entity_type', models.CharField(default='', max_length=1)),
                ('pid', models.CharField(db_index=True, max_length=26)),
                ('entity_full', models.TextField()),
                ('index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, default='', max_length=26)),
                ('nmlid', models.CharField(default='', max_length=300)),
                ('entity', models.CharField(default='', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Not yet determined'), (1, 'Match'), (2, 'No match'), (3, 'Unknown'), (4, 'Skip')], db_index=True, default=0)),
                ('kind', models.CharField(default='', max_length=300)),
                ('extras', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkKunstenaars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, default='', max_length=26)),
                ('nmlid', models.CharField(default='', max_length=300)),
                ('entity', models.CharField(default='', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Not yet determined'), (1, 'Match'), (2, 'No match'), (3, 'Unknown'), (4, 'Skip')], db_index=True, default=0)),
                ('kind', models.CharField(default='', max_length=300)),
                ('extras', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, default='', max_length=26)),
                ('nmlid', models.CharField(default='', max_length=300)),
                ('entity', models.CharField(default='', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Not yet determined'), (1, 'Match'), (2, 'No match'), (3, 'Unknown'), (4, 'Skip')], db_index=True, default=0)),
                ('kind', models.CharField(default='', max_length=300)),
                ('extras', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='linknew',
            unique_together={('pid', 'nmlid')},
        ),
        migrations.AlterUniqueTogether(
            name='linkkunstenaars',
            unique_together={('pid', 'nmlid')},
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('pid', 'nmlid')},
        ),
        migrations.AlterUniqueTogether(
            name='entities',
            unique_together={('doc_index', 'index')},
        ),
    ]
