# Generated by Django 2.0.4 on 2018-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=300)),
                ('article_date', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('nmlid', models.CharField(max_length=300)),
                ('died_date', models.CharField(max_length=300)),
                ('died_place', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=3)),
                ('kind', models.CharField(max_length=300)),
                ('extras', models.CharField(max_length=300)),
            ],
        ),
    ]
