# Generated by Django 2.0.4 on 2018-05-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='distance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
