# Generated by Django 2.0.4 on 2018-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_auto_20180530_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkKunstenaars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, default='', max_length=26)),
                ('nmlid', models.CharField(default='', max_length=300)),
                ('entity', models.CharField(default='', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Not yet determined'), (1, 'Match'), (2, 'No match'), (3, 'Unknown'), (4, 'Skip')], db_index=True, default=0)),
                ('kind', models.CharField(default='', max_length=300)),
                ('extras', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='linkkunstenaars',
            unique_together={('pid', 'nmlid')},
        ),
    ]
