CREATE TABLE entities (
	id int4 NOT NULL,
	entity varchar NOT NULL,
	entity_type bpchar(1) NOT NULL,
	pid bpchar(26) NOT NULL,
	entity_full varchar NOT NULL,
	"index" int4 NOT NULL
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX entities_entity_idx ON entities USING btree (entity) ;
CREATE INDEX entities_id_idx ON entities USING btree (id) ;
CREATE UNIQUE INDEX entities_id_index_idx ON entities USING btree (id, index) ;
CREATE INDEX entities_pid_idx ON entities USING btree (pid) ;
