# Generated by Django 2.0.4 on 2018-04-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_auto_20180410_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='died_date',
        ),
        migrations.RemoveField(
            model_name='link',
            name='died_place',
        ),
    ]
